apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.app_name }}
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.app_label }}
  template:
    metadata:
      labels:
        app: {{ .Values.app_label }}
    spec:
      containers:
      - name: {{ .Values.app_name }}
        image: {{ .Values.app_image }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "300m"
            memory: "300M"
          limits:
            cpu: "300m"
            memory: "300M"
  strategy:
    canary:
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 25
      - pause: { duration: 10m }
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.app_label }}
  ports:
    - port: 80
      targetPort: 8000
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.app_name }}
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{ .Values.app_name }}
  minReplicas: 5
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50